export default{
  homePage: 'https://magento.softwaretestingboard.com',
  login: 'https://magento.softwaretestingboard.com/customer/account/login/',
  email: '#email',
  password: '#pass',
  loginButton: '#send2',
  loggedIn: ':nth-child(2) > .greet > .logged-in',
  accountDropdown: ':nth-child(2) > .customer-welcome > .customer-name > .action',
  logOut: ':nth-child(2) > .customer-welcome > .customer-menu > .header > .authorization-link > a',
  firstName: '#firstname',
  lastName: '#lastname',
  emailAddress: '#email_address',
  passwordCreate: '#password',
  passwordConfirmation: '#password-confirmation',
  createAccountButton: '.action.submit.primary',
  errorMessage: '.message-error',
  username: '#user-name',
  categoryMan: '#ui-id-5 > :nth-child(2)',
  tops: 'dd > .items > :nth-child(1) > a',
  size: '.swatch-opt-724 > .size > .swatch-attribute-options > #option-label-size-143-item-166',
  addToCartButton: '[title="Add to Cart"]',
  sizeProduct: '#option-label-size-143-item-166',
  color: '#option-label-color-93-item-50',
  addToCartButtonProduct: '#product-addtocart-button',
  cartItems: '.showcart > .counter',
}